config/routes.rb
Rails.application.routes.draw do
devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  #admin
  namespace :admin do
    root 'homes#top'
    resources :customer_datas, only: [:show, :index, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :orders, only: [:index, :show]
    get '/customer_datas/:id/orders' => 'orders#index', as: "customer_data_orders" # 会員詳細 => 注文履歴の表示データを変える用
    get '/yesterday/orders' => 'orders#index', as: "yesterday_orders" # TOP,本日製作分の注文数 => 注文履歴の表示データ用
    get '/today/orders' => 'orders#index', as: "today_orders" # TOP,本日受注した注文数 => 注文履歴の表示データ用
    patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    patch '/orders/:id/item_status' => 'orders#item_status_update', as: "item_status" # 製作ステータスupdate
  end
  #customer
  root 'homes#top'
  get '/thanks' => 'homes#thanks' #サンクスページ
  get '/orders/confirm' => 'orders#confirm', as: 'orders_confirm' #購入確認画面への遷移
  get '/orders/create_order' => 'orders#create_order' #購入確定のアクション
  post '/orders/create_ship_address' => 'orders#create_ship_address' #情報入力画面での配送先登録用のアクション
  delete '/cart_items' => 'cart_items#destroy_all' #カートアイテムを全て削除
  resources :customers, only: [:show, :edit, :update]
  get '/customers/:id/withdrow' => 'customers#withdrow', as: 'withdrow_customer' #退会画面への遷移
  patch '/customers/:id/withdrow' => 'customers#switch', as: 'withdrow_switch_customer' #会員ステータスの切替
  resources :ship_addresses, except: [:new, :show]
  resources :cart_items, except: [:new, :show, :edit]
  resources :items, only: [:index, :show]
  resources :genres, only: [:index] do
  resources :items, only: [:index]
  end
  resources :orders, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   # エラー
   validates :quantity, presence: true
   # 数量0以下に変更して保存されないように
   belongs_to :customer
   belongs_to :item

   def validate_into_cart
      cart_items = self.customer.cart_items
      if (quantity) == nil
         return (false)
      elsif cart_items.any? {|cart_item| cart_item.item_id == (item_id)} == true
         return (false)
      else
        return (true)
      end
   end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

 def index
   @cart_items = current_customer.cart_items
   @total_price = calculate(current_customer)
 end

 def create
   @cart_item = CartItem.new(cart_item_params)
   @cart_item.customer_id = current_customer.id
   @validate_into_cart = @cart_item.validate_into_cart
   if @validate_into_cart == false
      flash[:into_cart_error] = "個数が選択されていないか、すでにカートに追加されているアイテムです。"
      redirect_to item_path(params[:cart_item][:item_id])
   else
     @cart_item.save
     redirect_to cart_items_path
   end
 end

 def update
   @cart_item = CartItem.find(params[:id])
   @cart_item.update(cart_item_params)
   redirect_to cart_items_path
 end

 def destroy
   cart_item = CartItem.find(params[:id])
   cart_item.destroy
   redirect_to cart_items_path
 end

 def destroy_all
   current_customer.cart_items.destroy_all
   redirect_to cart_items_path
 end

 private
 def cart_item_params
   params.require(:cart_item).permit(:customer_id, :item_id, :quantity)
 end

 def calculate(user)
   total_price = 0
   user.cart_items.each do |cart_item|
     total_price += cart_item.quantity * cart_item.item.price
   end
   return (total_price * 1.1).floor
 end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container my-5">
    <div class="row">
      <div class="offset-1">
        <h2 class="red-border px-3 pb-1">ショッピングカート</h2>
      </div>

      <div class="ml-auto">
        <%= link_to "カートを空にする", cart_items_path, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>

    <div class="row mt-5">
      <div class="offset-1 col-9">
        <table class="table table-borderless">
          <thead>
            <tr class="red-border">
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <% @cart_items.each do |cart_item| %>
            <tbody>
              <tr class="brown-border">
                <td class="align-middle">
                  <%= attachment_image_tag cart_item.item, :image, size: "50x50", fallback: "no_image.jpg" %>
                  <span><%= cart_item.item.name %></span>
                </td>
                <td class="align-middle"><%= (cart_item.item.price * 1.1).floor %></td>
                <td class="align-middle" style="width: 130px;">
                  <%= form_for(cart_item) do |f| %>
                  <div class="row">
                    <%= f.number_field :quantity, min:1,class: "col-6" %>
                    <%= f.submit "変更", class: "btn btn-sm btn-outline-danger offset-1 col-4" %>
                  </div>
                  <% end %>
                </td>

                <td class="align-middle">
                  <%= (cart_item.item.price * 1.1).floor * cart_item.quantity %>
                </td>

                <td class="align-middle"><%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn btn-sm btn-danger" %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>

      <div class="row my-3">
        <div class="offset-9">
          <strong class="red-border px-3 pb-1">合計金額 <%= @total_price %>円</strong>
        </div>
      </div>

    <div class="row">
      <div class="offset-1 col-2">
        <%= link_to "買い物を続ける", items_path, class: "btn btn-outline-danger mt-5" %>
      </div>
      <% if @cart_items != [] %>
      <div class="offset-6">
        <%= link_to "情報入力に進む", new_order_path, class: "btn btn-outline-danger mt-5" %>
      <% end %>
      </div>
    </div>
</div>